### ISSUE TITLE
Alienware 15 R2 with 4720HQ

### ISSUE THREAD

**Issue by wxunyang** [RockJesus/Alienware-Hackintosh#6]
Hi, @RockJesus 

My installation was stopped after "voodooi2c" with a banned mark, what should i do?
![image](https://user-images.githubusercontent.com/33387570/70386255-9a410380-19d2-11ea-9d85-096ec00d940f.png)

**Comment by RockJesus** [comment]
use post-install

**Comment by wxunyang** [comment]
> use post-install

thanks. I've already sucessfully installed 10.14 with other clover settings. (but 10.15 still fail)
